name: deno

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.7.2
      - name: Lint
        run: deno lint --unstable

  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.7.2
      - name: Format
        run: |
          deno fmt --check

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.7.2
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: false
          version: v8.2.2525
      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
          version: stable
      - name: Test
        run: |
          deno test --allow-run --allow-net --allow-env
        env:
          DENOPS_VIM: ${{ steps.vim.outputs.executable }}
          DENOPS_NVIM: ${{ steps.nvim.outputs.executable }}
